OSOE-867: Update analyzer packages to latest in Lombiq.Analyzers
Lombiq/.NET-Analyzers pull request #101
Opened 2024-06-08 14:26 UTC by Psichorex

OSOE-867

2024-06-10 19:53 UTC, Piedone requested changes

2024-06-10 19:53 UTC, Piedone commented on Lombiq.Analyzers/AnalyzerPackages.props
> +    <AnalyzerPackage Include="Microsoft.CodeAnalysis.CSharp.CodeStyle" Version="4.9.2"/>
The latest is 4.10.0 now.

2024-06-11 11:56 UTC, Psichorex commented on Lombiq.Analyzers/AnalyzerPackages.props
> +    <AnalyzerPackage Include="Microsoft.CodeAnalysis.CSharp.CodeStyle" Version="4.9.2"/>
Yap also 9.27.0.93347 for Sonar

2024-06-11 19:45 UTC, Piedone approved these changes

2024-06-11 21:20 UTC, merged