FINI-640: Update static code analyzer packages
Lombiq/.NET-Analyzers pull request #21
Opened 2021-03-11 20:05 UTC by Piedone

2021-03-13 20:19 UTC, DAud-IcI requested changes

2021-03-13 20:19 UTC, DAud-IcI commented on OrchardCore.ruleset
> +  <Include Path="general.ruleset" Action="Default" />
Miért? A fájl nagy G-vel van és szerintem ezzel a változtatással csak azt érjük el, hogy case sensitive fájlrendszereken ne működjön ami nem egy pozitív fejlemény.

2021-03-15 19:16 UTC, Piedone commented on OrchardCore.ruleset
> +  <Include Path="general.ruleset" Action="Default" />
Valóban, de ezt nem én csinálom, hanem a VS ruleset editorja :(. Valszeg nem számít nek case-sensitive fájlrendszeren sem. De reverteltem.

2021-03-15 19:45 UTC, DAud-IcI commented on OrchardCore.ruleset
> +  <Include Path="general.ruleset" Action="Default" />
Terminátor 3: A gépek lázadása

2021-03-15 19:46 UTC, merged