VSIX-37: Static code analysis integration
Lombiq/.NET-Analyzers pull request #33
Opened 2021-11-11 19:56 UTC by boros-csaba

VSIX-37

2021-11-12 01:27 UTC, Piedone requested changes

2021-11-12 01:27 UTC, Piedone commented on VisualStudioExtension.ruleset
> +    <Rule Id="CA2007" Action="None" />
Ezt miért kell kikapcsolni?

2021-11-12 01:27 UTC, Piedone commented on VisualStudioExtension.ruleset
> +    <Rule Id="VSTHRD200" Action="Warning" />
Hmm, érdekes, hogy ez eddig nem volt a Generalban bekapcsolva, csak az OC, O1 rulesetben. Légyszi inkább csak a Generalban legyen.

2021-11-14 17:53 UTC, boros-csaba commented on VisualStudioExtension.ruleset
> +    <Rule Id="CA2007" Action="None" />
"Do not directly await a Task" - ez a rule szerint minden await esetében kellene használni a ConfigureAwait(true/false) hívást. Más projektekben sem láttam ezt használva és Gábort is kérdeztem róla, neki sem volt ismerős.

2021-11-14 18:16 UTC, boros-csaba commented on VisualStudioExtension.ruleset
> +    <Rule Id="VSTHRD200" Action="Warning" />
Átraktam a VSTHRD200 bekapcsolását a general.ruleset-be, de nem láttom sem az OrcherdCore sem az Orchard1-ben.

2021-11-14 22:25 UTC, Piedone commented on VisualStudioExtension.ruleset
> +    <Rule Id="CA2007" Action="None" />
Ugye ez akkor érdekes, ha külön UI thread van, azaz ha az app mondjuk egy desktop WPF app, vagy VS extension. Szóval itt érvényes az ajánlás szerintem. Webappoknál nem.

2021-11-14 22:27 UTC, Piedone commented on VisualStudioExtension.ruleset
> +    <Rule Id="VSTHRD200" Action="Warning" />
Mármint hogy érted, hogy nem látod? Ha így megnyitod a ruleset fájlt VS-ben, akkor látnod kell benne az összes, általa include-olt rulesetből származó rule configját is:

![image](https://user-images.githubusercontent.com/1976647/141701024-6e76de26-b679-4236-9a8a-7edf2040c7cb.png)

2021-11-21 09:40 UTC, boros-csaba commented on VisualStudioExtension.ruleset
> +    <Rule Id="VSTHRD200" Action="Warning" />
Az Orchard1.ruleset-ben nem látom, hogy külön be lenne kapcsolva:
![image](https://user-images.githubusercontent.com/18496537/142757006-ff9cfd8b-adbd-4909-9235-71cebdbfb55c.png)

2021-11-21 09:44 UTC, boros-csaba commented on VisualStudioExtension.ruleset
> +    <Rule Id="CA2007" Action="None" />
Visszakapcsoltam

2021-11-21 23:20 UTC, Piedone commented on VisualStudioExtension.ruleset
> +    <Rule Id="VSTHRD200" Action="Warning" />
Az nem jelenti azt, hogy ne lenne bekapcsolva, mert ahogy említettem, az általa include-olt (OrchardCore.ruleset) fájlban is lehet ez (meg az általa include-oltban is). Továbbá by default is be lehet kapcsolva. Nézd meg VS-ben, ahogy mutattam.

2021-11-25 07:46 UTC, boros-csaba commented on VisualStudioExtension.ruleset
> +    <Rule Id="VSTHRD200" Action="Warning" />
Okés, köszi. Ott van.

2021-11-29 22:12 UTC, Piedone requested changes

2021-11-29 22:12 UTC, Piedone commented on VisualStudioExtension.Build.props
> +    <CodeAnalysisRuleSet>$(MSBuildThisFileDirectory)Orchard1.ruleset</CodeAnalysisRuleSet>
Ez nem kell.

2021-11-29 22:12 UTC, Piedone commented on VisualStudioExtension.Build.props
> +	<CodeAnalysisRuleSet>$(MSBuildThisFileDirectory)VisualStudioExtension.ruleset</CodeAnalysisRuleSet>
Ezt a sort leszámítve ez a NetFx.Build.props másolata. E helyett DRY-olni kellene (a CommonPackages.props használata is ilyen).

2021-11-30 20:57 UTC, boros-csaba commented on VisualStudioExtension.Build.props
> +    <CodeAnalysisRuleSet>$(MSBuildThisFileDirectory)Orchard1.ruleset</CodeAnalysisRuleSet>
Kitöröltem

2021-11-30 20:57 UTC, boros-csaba commented on VisualStudioExtension.Build.props
> +	<CodeAnalysisRuleSet>$(MSBuildThisFileDirectory)VisualStudioExtension.ruleset</CodeAnalysisRuleSet>
Kiemeltem a közös részeket egy új fájlba Common.Build.props-ba

2021-11-30 20:57 UTC, boros-csaba commented on VisualStudioExtension.Build.props
> +    <CodeAnalysisRuleSet>$(MSBuildThisFileDirectory)Orchard1.ruleset</CodeAnalysisRuleSet>
Kitöröltem

2021-12-01 16:25 UTC, Piedone requested changes

2021-12-01 16:25 UTC, Piedone commented on Common.Build.props
> +<Project>
Mivel ez csak a .NET Framework projecteknek érdekes, legyen inkább NetFxCommon.Build.props. De amúgy nem lehet minden innen a NetFx.Build.props-ban csak, és a VSIX props abból származtat? Nem lehet úgy felülírni a használt ruleset fájlt?

2021-12-01 17:33 UTC, boros-csaba commented on Common.Build.props
> +<Project>
Töröltem a Common.Build.props-ot. A VisualStuioExtension.Build.props most a NetFx.Build.props-ból számazik és felülírja a CodeAnalysisRuleSet property-t

2021-12-01 22:28 UTC, Piedone approved these changes

2021-12-02 15:19 UTC, merged