OSOE-485: Update GitHub Actions workflows of all OSOCE projects from the OSS template
Lombiq/.NET-Analyzers pull request #83
Opened 2023-01-31 11:13 UTC by DJdisco07

2023-02-02 21:17 UTC, wAsnk requested changes

2023-02-02 21:17 UTC, wAsnk commented on .github/workflows/validate-pull-request.yml
> +    uses: Lombiq/GitHub-Actions/.github/workflows/validate-pull-request.yml@dev
Same, please check other PRs as well.

2023-02-02 21:29 UTC, DJdisco07 commented on .github/workflows/validate-pull-request.yml
> +    uses: Lombiq/GitHub-Actions/.github/workflows/validate-pull-request.yml@dev
pushed the commit

2023-02-03 12:52 UTC, wAsnk approved these changes

2023-02-06 22:00 UTC, merged