Migrate to .editorconfig from ruleset files
Lombiq/.NET-Analyzers pull request #93
Opened 2023-10-10 19:54 UTC by Piedone

2023-10-13 13:38 UTC, BenedekFarkas requested changes

2023-10-13 13:38 UTC, BenedekFarkas commented on Lombiq.Analyzers/Docs/AddingAnalyzers.md
> +If you don't want to stay on the cutting-edge version, nor do you intend to contribute to Lombiq .NET Analyzers, you can use one of the NuGet packages. Install the package suitable for your project,
```suggestion
If you don't want to stay on the cutting-edge version, nor do you intend to contribute to Lombiq .NET Analyzers, you can use one of the NuGet packages. Install the package suitable for your project, as described above. Check for the latest version number [on NuGet](https://www.nuget.org/packages/Lombiq.Analyzers/).
```

2023-10-13 13:38 UTC, BenedekFarkas commented on Lombiq.Analyzers/Docs/AddingAnalyzers.md
> +2. Create a _Directory.Build.props_ file in every project folder you want to target, next to the _.csproj_ file with the following content, either referencing `Lombiq.Analyzers.NetFx` or `Lombiq.Anal
If all the projects that you want analyzed have a common ancestor folder that only contains the projects you want analyzed, then you can get away with a single _Directory.Build.props_ file here too, right?

2023-10-13 13:38 UTC, BenedekFarkas commented on Lombiq.Analyzers/Lombiq.Analyzers.VisualStudioExtension.globalconfig
Isn't this a leftover duplicate of [Lombiq.Analyzers.VisualStudioExtension/Lombiq.Analyzers.VisualStudioExtension.globalconfig](https://github.com/Lombiq/.NET-Analyzers/pull/93/files#diff-ea78335fdbc3ac7ffd79417cdf890280fb782d659fb5dd7987a0fdaf5dac7cbe)?

2023-10-13 13:42 UTC, BenedekFarkas requested changes

2023-10-13 13:42 UTC, BenedekFarkas commented on Lombiq.Analyzers.NetFx/NuGetIcon.png
NuGetIcon.png and Readme.md must duplicated between the analyzer sub-projects, right? I was thinking that it would be nicer to have them in a common folder one level above and reference them from there, but then the path won't match up for NuGet package, I guess. Maybe a copy task in the sub-projects' csproj to copy them to the right place?

2023-10-13 13:42 UTC, BenedekFarkas commented on Lombiq.Analyzers.Orchard1/Lombiq.Analyzers.Orchard1.globalconfig
Are the new .globalconfig files together completely supersede Lombiq.Analyzers/.editorconfig? I'm asking, because there are a lot more rules deleted from the latter compared to what's in the new files.

2023-10-16 13:38 UTC, Piedone commented on Lombiq.Analyzers/Docs/AddingAnalyzers.md
> +2. Create a _Directory.Build.props_ file in every project folder you want to target, next to the _.csproj_ file with the following content, either referencing `Lombiq.Analyzers.NetFx` or `Lombiq.Anal
Yep. This is here because in O1 you usually don't have that, but I've clarified this.

2023-10-16 13:38 UTC, Piedone commented on Lombiq.Analyzers/Lombiq.Analyzers.VisualStudioExtension.globalconfig
It is.

2023-10-16 13:44 UTC, Piedone commented on Lombiq.Analyzers.NetFx/NuGetIcon.png
The Readmes are unique to each project.

NuGetIcon does need to be duplicated in all submodules of OSOCE (for the NuGet publishing to work independently in each of their repos) but it indeed doesn't necessarily need to be duplicated in all projects of these submodules. However, this is done automatically by [this target](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/blob/dev/Directory.Build.props#L17).

We could optimize this to only have a single copy per submodule, but that seems like a lot of work and attention needed for muli-project repos just to save a copy of instances of a 5 KB file (there wouldn't be any other benefit than storage; we already have DRY with the OSOCE target).

2023-10-16 13:53 UTC, Piedone commented on Lombiq.Analyzers.Orchard1/Lombiq.Analyzers.Orchard1.globalconfig
They overlap but .editorconfig is still needed. Editor-specific config, like charset, guidelines, tabs, need to be in .editorconfig (since such configs aren't supported by .globalconfig, and non-.NET editors only understand .editorconfig). Analyzer configs can be in .editorconfig but the recommended way is to put them into .globalconfigs, since on contrary to .editorconfig those files can be referenced in a csproj instead of having to be copied to the folder structure.

So, editor configs should be in .editorconfig, analyzer configs in .globalconfigs.  I thus moved all the analyzer configs from the .editorconfig to the main Lombiq.Analyzers.globalconfig, cleaned it up, as well as added the analyzer configs migrated from .ruleset files there.

2023-10-16 14:00 UTC, BenedekFarkas commented on Lombiq.Analyzers.NetFx/NuGetIcon.png
OK - BTW I meant to write License.md instead of Readme, but it's the same story as NuGetIcon.png (or even less common, because the year might be different).

2023-10-16 16:27 UTC, BenedekFarkas commented on Lombiq.Analyzers.Orchard1/Lombiq.Analyzers.Orchard1.globalconfig
OK, thanks! What caught my eye at first is how much stuff was deleted from `.editorconfig`, but not so much was added to the subfolders' `.globalconfig` files. But I didn't look at the root `.globalconfig` (`Lombiq.Analyzers/Lombiq.Analyzers.globalconfig`), which is mostly the successor of `Lombiq.Analyzers/.editorconfig`, so I understand now!

2023-10-16 16:30 UTC, BenedekFarkas approved these changes

2023-10-16 16:47 UTC, merged